#!/bin/bash
MSG=$(git log -1 --pretty=%B)
if [[ $MSG =~ \[doc\] ]]; then
    bundle exec rdoc -o ../dacp-gh-pages/doc dacp
    cd ../dacp-gh-pages
    CHANGED=$(git ls-files -m)
    if [ "doc/created.rid" != "$CHANGED" ]; then
        git add . && git commit -m"$MSG"
        echo "Documentation updated commited";
    else
        echo "Documentation unchanged";
    fi
fi
